# NumPy Notes

In [ ]:
## NumPy is a python library used for working with arrays. NumPy is short for Numerical Python. 
# --> It also has functions of working in domain of linear algebra, fourier transform and matrices

In [ ]:
# Why use NumPy?
# The lists in python are sloe to process, NumPy provides an array 50 times faster

'''The array object in python is called ndarray'''

# Why NumPy is faster than lists?
# --> NumPy arrays are stored at one continuous location in memory, so processes can access 
#     and manipulate them effeciently. It is also optimized to work with latest CPU architectures.

# Continuous memory location behaviour is called as locality of reference.

# Which language python is written in?
# --> Partially in python, but most of the parts that require faster computation are written in C or C++.

In [3]:
import numpy

arr = numpy.array([1,2,3,4,5,6])

arr

array([1, 2, 3, 4, 5, 6])

In [2]:
# NumPy is always imported under np alias

import numpy as np

arr = np.array([1,2,3,4,5,6])  # using np instead of numpy

arr

array([1, 2, 3, 4, 5, 6])

In [3]:
np.__version__    # check version of numpy installed in your device

'1.24.3'

In [4]:
# CREATE A NumPY ndarray OBJECT

# The array object in Numpy is called ndarray. We can create a ndarray using array() function.

arr = np.array([1,2,3,4,5,6])

print(type(arr))


<class 'numpy.ndarray'>


In [ ]:
# type() : built in python function, returns the type of the object passed to it.

In [ ]:
'''If we pass any list, tuple, or any array-like object to array() function, it will be converted into ndarray'''

In [ ]:
# nested array: are arrays that have arrays as their elements.

In [11]:
# -------------------- DIMENTIONS IN ARRAYS -------------------------- #

# 0-D ARRAY:

# Each value in an array is a 0-D array.

arr0 = np.array(42)

arr0

array(42)

In [12]:
# 1-D Arrays:

# An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

arr1 = np.array([1,2,3,4,5,6])

arr1

array([1, 2, 3, 4, 5, 6])

In [13]:
# 2-D Arrays:

# Has 1-D array as its elements. Often used to represent matrix

'''NumPy has a whole sub module dedicated towards matrix operations called numpy.mat'''

arr2 = np.array([[1,2,3], [8,7,6]])

arr2

array([[1, 2, 3],
       [8, 7, 6]])

In [14]:
# 3-D Arrays:

# Has 2-D Arrays as its elements.

arr3 = np.array([[[1,2,3], [4,5,6],[2,3,4],[7,9,6]]])

arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [2, 3, 4],
        [7, 9, 6]]])

In [15]:
# Check number of dimensions using .ndim 

print(arr0.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

0
1
2
3


In [19]:
# Higher dimensional array

#  - An array can have any number of dimensions
#  - After creating an array you can define the number of dimensions using "ndmin" argument

arr = np.array([1,2,3,4,5], ndmin = 5)

print(arr)

print(arr.ndim)

[[[[[1 2 3 4 5]]]]]
5


In [26]:
# ------------------------ NumPy Array Indexing ------------------------------ #

# Accessing the elements of numpy array with index value
# 1-D array
arr = np.array([1,2,3,4,5])

print(arr[0])
print(arr[3])

# Get last element
print(arr[-1])

# get the elements from specified indexes and add them and format with f-string
print(f"sum = {arr[3] + arr[4]}") 

1
4
5
sum = 9


In [28]:
# 2-D array
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

# get second element from first row in a 2-D array

print(arr[0,1])

# get second element from first row in a 2-D array

print(arr[1, 3])


2
9


In [62]:
# 3-D array

arr = np.array([[[1,2,3,4,5], [6,7,8,9,10], [0,3,6,1,8], [11,12,13,14,15]]])

print("Array : ", arr)

print("First element : ",arr[0,0,0])

print("Second element in third row : ",arr[0,2,2])

print("last element in fourth row : ",arr[0,3,-1])

# SYNTAX : [Axis(in this example its 0 always), no. of row(0/1/2/3), position of element]



Array :  [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [ 0  3  6  1  8]
  [11 12 13 14 15]]]
First element :  1
Second element in third row :  6
last element in fourth row :  15


In [46]:
# ------------------- Negative Indexing ------------------------- #

arr = np.array([[1,2,3,4,5], [3,4,9,6,5]])

print("Last Element in second row : ", arr[1, -1])

print("middle Element in first row : ", arr[0, -3])



Last Element in second row :  5
middle Element in first row :  3


In [55]:
# ------------------------------ NumPy ARRAY SLICING -------------------------------- #

'''

----->   [start : end]

----->   [start : end : step]

'''

# If start is not passed its considered 0
# If end is not given its considered lrngth of array
# If step is not considered its considered 1


arr = np.array([2,6,3,1,8,9,4,3,2,1,0,5,1,12])

print("A slice from 0 to 2: ",arr[0:3]) # Gives till 2 end is not included

print("start at zero, till end of array, with step 2: ",arr[0: : 2])


# The result includes the start index, but excludes the end index.

A slice from 0 to 2:  [2 6 3]
start at zero, till end of array, with step 2:  [2 3 8 4 2 0 1]


In [61]:
# Negative Slicing

print(arr[-5: -1]) # here end is not included

print(arr[-5: ]) # here it goes till end value

[1 0 5 1]
[ 1  0  5  1 12]


In [79]:
# STEP - Using step value to determine the step of slicing

arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[-1: :2])

print(arr[1: :2])

# return every other element of entire array
print(arr[ : : 2])

print("Reversed value with step of -2: ",arr[-1: :-2]) 

print("Reversing array with negative indexing:",arr[-1::-1]) 


[10]
[ 2  4  6  8 10]
[1 3 5 7 9]
Reversed value with step of -2:  [10  8  6  4  2]
Reversing array with negative indexing: [10  9  8  7  6  5  4  3  2  1]


In [87]:
# Slicing 2-D arrays
# Syntax: arr[indexOfRow, start:End:Step]

arr = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,18,20]])

print("In first row, all ele from index 5: ",arr[0, 5: ])

print("reversed second row: ",arr[1, -1: : -1])

print("Print numbers from both arrays:", arr[0:2, 0::1])

'''Here first 0:2 indicates row numbers from 0 to 1 as 2 will not be included. If we specify 0:1 it will only print 
0th(first) row.
'''


In first row, all ele from index 5:  [ 6  7  8  9 10]
reversed second row:  [20 18 18 17 16 15 14 13 12 11]
Print numbers from both arrays: [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 18 20]]


'Here first 0:2 indicates row numbers from 0 to 1 as 2 will not be included. If we specify 0:1 it will only print \n0th(first) row.\n'

In [88]:
# ---------------------------- NumPy Data Types ---------------------------------- #

'''  DATA TYPES IN PYTHON '''

'''

1: string ----> "It is a string"
2: boolean ---> True/False
3: integer ---> 10
4: float -----> 12.00
5: complex ---> 2.5 + 1.0j

'''

# DATA TYPES IN NUMPY -- Numpy refers to datatypes with one character

'''
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

'''

'\ni - integer\nb - boolean\nu - unsigned integer\nf - float\nc - complex float\nm - timedelta\nM - datetime\nO - object\nS - string\nU - unicode string\nV - fixed chunk of memory for other type ( void )\n\n'

In [89]:
# Checking the datatype of an array

arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


In [90]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)   #U - unicode string

<U6


In [91]:
# Creating arrays with a defined data type

arr=np.array([1,2,3,4,5,6,7], dtype='S') #S - string

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5' b'6' b'7']
|S1


In [92]:
arr = np.array(['a', '2', '3'], dtype='i')

# python raises value error when it cannot convert a value to another datatype. here python is unable to convert 
# 'a' to integer.

ValueError: invalid literal for int() with base 10: 'a'

In [94]:
# Converting datatype of an existing array 

'''
.astype('i')

'''

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [1]:
# NumPy Array Copy vs View

'''
- Main difference between copy and view is Copy is a new array and view is just a view of original array.
- Copy owns its data. If any changes are made in copy it will not reflect in main array and vice versa.

- View does not own the data. If any changes are made in the view they reflect in original array 
and any changes made in original array reflect in view.

'''


'\n- Main difference between copy and view is Copy is a new array and view is just a view of original array.\n- Copy owns its data. If any changes are made in copy it will not reflect in main array and vice versa.\n\n- View does not own the data. If any changes are made in the view they reflect in original array \nand any changes made in original array reflect in view.\n\n'

In [2]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])

newArr = arr.copy()

print(arr)
print(newArr)

[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]


In [4]:
# Now we will try to make changes in copy/original view and see if these changes reflect in the other one.

arr[0]= 100
print(arr)
print(newArr)

newArr[0] = 200
print(arr)
print(newArr)



[100   2   3   4   5   6   7   8]
[1 2 3 4 5 6 7 8]
[100   2   3   4   5   6   7   8]
[200   2   3   4   5   6   7   8]


In [5]:
# We can see if we change a value in one array, it does not reflect in another.

In [9]:
arr = np.array([1,2,3,4,9,8,7,6])

newArr = arr.view()

print(arr)
print(newArr)

[1 2 3 4 9 8 7 6]
[1 2 3 4 9 8 7 6]


In [10]:
newArr[0] = 100

print(arr)
print(newArr)

[100   2   3   4   9   8   7   6]
[100   2   3   4   9   8   7   6]


In [ ]:
# Tnhis shows any chnages made in one reflects in other.

In [11]:
# Checking if array owns its data

'''
- Every NumPy array has the attribute called 'base' which return None is the array owns data,
otherwise base refers to the original object.

'''

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()    # copy owns data
y = arr.view()    # View does not own the data

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [23]:
# Numpy Array Shape

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)   # gives (rows,columns)

(2, 4)


In [25]:
arr = np.array([1, 2, 3, 4],ndmin=5)
                
print(arr.shape)

# Integers at every index tells about the number of elements the corresponding dimension has.

# In the example above at index-4 we have value 4, so we can say that 5th ( 4 + 1 th) dimension has 4 elements.

(1, 1, 1, 1, 4)


# Numpy Array Reshaping



### Reshaping --> changing the shape of an array
### Shape of array --> Number of elements in each dimension

### By reshaping we can --> Add or remove dimensions or change number of elements in each dimension

### arr.reshape() --- >  Function

In [6]:
# reshape from 1-D to 2-D
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4,3)

print(newarr)

# Converting an 1-D array into a 2-D array

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
# Converting into a 3-D array

newarr = arr.reshape(2,3,2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [8]:
''' We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot 
reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements'''

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr)

# This code will give an error

ValueError: cannot reshape array of size 8 into shape (3,3)

In [9]:
# Unknown Dimension

# We can have one "unknown" dimension.

# Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

# Pass -1 as the value, and NumPy will calculate this number for you.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# -1 cannot be passed to more than one dimension

# Flattering the array

In [12]:
# This means converting an multidimensional array into a 1-D array.

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6 7 8]


In [ ]:
# reshape(-1) --> function

'''
There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for 
rearranging the elements rot90, flip, fliplr, flipud etc. These fall under Intermediate to Advanced 
section of numpy.

'''

# Numpy Array Iterating

In [13]:
# Iterating --> going through array elements one by one

# 1-D Array

arr = np.array([1,2,3,4,5,6])

for x in arr:
    print(x)


1
2
3
4
5
6


In [17]:
# 2-D Array

import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

for x in arr:
    print(x)
    
# Here it takes 1 row of a 2-D array as 1 element.

[1 2 3 4 5]
[ 6  7  8  9 10]


In [18]:
# In above example we are not iterating through each element, 
# to do so we have to iterate the array in each dimension

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9
10


In [20]:
# Iterating 3-D array

arr = np.array([[[1,2,3],[4,5,6]],[[5,4,1], [8,7,9]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
5
4
1
8
7
9


# Iterating array using nditer()

In [21]:
# nditer() -->  function used to iterate over very basic to very advanced functions

'''In basic for loops, iterating through each scalar of an array we need to use n for loops
which can be difficult to write for arrays with very high dimensionality.'''

'In basic for loops, iterating through each scalar of an array we need to use n for loops\nwhich can be difficult to write for arrays with very high dimensionality.'

In [22]:
# implementing same example of 3-D array with nditer()

arr = np.array([[[1,2,3],[4,5,6]],[[5,4,1], [8,7,9]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
5
4
1
8
7
9


In [24]:
# Iterating array with different datatypes

arr = np.array([1,2,3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


In [38]:
# iterating with different step size

arr = np.array([[[1,2,3],[4,5,6]],[[5,4,1], [8,7,9]]])

for x in np.nditer(arr[:, 1::2]):
    print(x)


4
5
6
8
7
9


In [39]:
# Enumerated Iteration using ndenumerate()

# Enumeration --> Mentioning sequence number of something one by one

arr = np.array([1,3,8,7])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 3
(2,) 8
(3,) 7


In [40]:
arr = np.array([[1,3,8,7],[4,5,6,3]])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 3
(0, 2) 8
(0, 3) 7
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 3


# Numpy joining Array

In [ ]:
# Joining: putting contents of two or more array together

# In NumPy we join arrays by axes.

''' 

concatenate()  --> function used to join arrays

'''

# We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis.
# If axis is not explicitly passed, it is taken as 0.



In [42]:
arr1 = np.array([1,2,3,4,5])

arr2 = np.array([6,7,8,9,5])

newarr = np.concatenate((arr1, arr2))

print(newarr)

[1 2 3 4 5 6 7 8 9 5]


In [43]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


## Joining Arrays using stack function

In [44]:
# Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
# We pass a sequence of arrays that we want to join to the stack() method along with the axis. 
# If axis is not explicitly passed it is taken as 0.

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [45]:
# Stacking Along rows
'''
hstack()
'''

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [46]:
# stacking along column

'''
vstack()
'''

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [47]:
# stacking along height (Depth)

'''
dstack()

'''

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# Numpy Splitting Array

In [52]:
# splitting breaks one array into multiple

''' array_split()'''

arr1 = np.array([1,2,3,4,5,2,7,8])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[[1, 4],
        [2, 5],
        [3, 6]]]), array([], shape=(0, 3, 2), dtype=int64), array([], shape=(0, 3, 2), dtype=int64)]


In [55]:
# If there are no enough elements for split, the function adjusts from the end
arr1 = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([[[1, 4],
        [2, 5],
        [3, 6]]]), array([], shape=(0, 3, 2), dtype=int64), array([], shape=(0, 3, 2), dtype=int64), array([], shape=(0, 3, 2), dtype=int64)]


In [ ]:
'''We also have the method split() available but it will not adjust the elements when elements are less 
in source array for splitting like in example above,array_split() worked properly but split() would fail.'''

# split into arrays

In [2]:
# array_split() --> this method returns an array containing each of the slpit as an array

# If you split an array into 3 arrays, you can access them from the result just like any array element:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [6]:
# splitting 2-D arrays:

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

# splitting along the row (axis)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [10]:
# An alternate solution is using hsplit() opposite of hstack() -> (instead of above example)

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
''' Similar alternates to vstack() and dstack() are available as vsplit() and dsplit(). '''

# NumPy Searching Arrays

In [12]:
# Search an array for a certain value and return indexes of the match

'''
where()  --> method to search an array

'''

arr = np.array([1,2,3,4,5,6,4,4,2,8,9,4,3,4])

x = np.where(arr == 4)

print(x)  # returns all indexes where 4 is present

(array([ 3,  6,  7, 11, 13]),)


In [13]:
# Find indexes where values are even

arr = np.array([1,2,3,4,5,6,7,8,9,10])

x = np.where(arr % 2 == 0)

print(x) # returns indexes where value is even

(array([1, 3, 5, 7, 9]),)


In [14]:
# Find indexes where values are odd

arr = np.array([1,2,3,4,5,6,7,8,9,10])

x = np.where(arr % 2 == 1)

print(x) # returns indexes where value is odd

(array([0, 2, 4, 6, 8]),)


In [ ]:
'''
searchsorted() --> Assumed to be used on sorted array.
Performs binary search and returns the index where specified value is assumed to be inserted.

'''

In [15]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x) # outputs index

# The method starts the search from the left and returns the first index where the 
# number 7 is no longer larger than the next value.

1


In [16]:
# Search From the Right Side
# By default the left most index is returned, but we can give side='right' to return the right most index instead.

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x) # index 2

2


# Searching multiple values

In [17]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x) # returns indexes

[1 2 3]


# NumPy Sorting Arrays

In [ ]:
# Sorting means putting elements in an ordered sequence.

# Ordered sequence is any sequence that has an order corresponding to elements, 
# like numeric or alphabetical, ascending or descending.

# The NumPy ndarray object has a function called sort(), that will sort a specified array.


In [19]:
arr = np.array([1,6,3,7,2])

newarr = np.sort(arr)
print(newarr)

[1 2 3 6 7]


In [20]:
#  sort array alphabetically

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [21]:
# Sort a boolean array:

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [22]:
# Sorting a 2-D Array
# If you use the sort() method on a 2-D array, both arrays will be sorted:

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# NumPy Array filter

In [ ]:
# # Getting some elements out of an existing array and creating a new array out of them is called filtering.

# In NumPy, you filter an array using a boolean index list.

# A boolean index list is a list of booleans corresponding to indexes in the array.

'''If the value at an index is True that element is contained in the filtered array, 
if the value at that index is False that element is excluded from the filtered array.'''

In [23]:
arr = np.array([32,40,21,56,89])

x = [True, False,True,False,False]

newarr = arr[x]

print(newarr)

[32 21]


### Creating the filter array

In [25]:
#  In the example above we hard-coded the True and False values, 
# but the common use is to create a filter array based on conditions.

arr = np.array([1,43,23,67,54,99,0,31,52,48])

filter_arr = []

for element in arr:
    if element > 40:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]

print(newarr)

[43 67 54 99 52 48]


In [29]:
#  Create a filter array that will return only even elements from the original array:

arr = np.array([1,43,23,67,54,99,0,31,52,48])

filter_arr = []

for element in arr:
    if (element % 2 == 0):
        filter_arr.append(True)    
    else:
        filter_arr.append(False)
        
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)  


[False, False, False, False, True, False, True, False, True, True]
[54  0 52 48]


In [30]:
# Creating filter directly from array

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [31]:
arr = np.array([1,2,3,4,5,6,7,8])

filter_arr = (arr % 2 == 0)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False  True]
[2 4 6 8]
